on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: trybe-wallet_trybewallet
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: trybe-wallet_trybewallet
      id: trybe-wallet_trybewallet
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        docker_registry_url: 'docker.pkg.github.com'
        docker_registry_owner: 'underewarrr'
        docker_repository: 'action-bpd'
        docker_image: 'bpdautolatest'
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
        dockerfile: 'Dockerfile'
    - name: Get the output
      run: |
          echo "imageinfo was ${{ steps.test.outputs.imageinfo }}"
