name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: manusa/actions-publish-docker@v1.1.2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trybe-wallet_trybewallet:$(date +%s)
